### ISSUE TITLE
PWMOut object has no period attribute

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Blinka#125]
```
>>> led.period
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PWMOut' object has no attribute 'period'
```
PWMOut 's period methods need something similar to: https://github.com/adafruit/Adafruit_Blinka/blob/master/src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py#L212

**Comment by makermelissa** [comment]
Fixed by #126
