### ISSUE TITLE
raspi_1a support (26 pin model a)

### ISSUE THREAD

**Issue by schustykd** [adafruit/Adafruit_Blinka#153]
looking for help with blinka support for board id: RASPBERRY_PI_A (26 pin, raspberry pi 1, model a, 2011.12).

am thinking that it is not currently supported, but i'm new at this, so would appreciate advice if i'm missing something.

detect.py correctly identifies my board as RASPBERRY_PI_A but blinkatest.py fails with "Board not supported".

thanks in advance.

**Comment by makermelissa** [comment]
Thanks for posting this @schustykd. I'm gonna try and trace down why it's not working on the Pi 1 A in the code, but I don't currently have one so I may need you to test it.

**Comment by schustykd** [comment]
I can do that, no problem.  Let me know how I can help.

**Comment by makermelissa** [comment]
I have a PR #155 in if you want to try that out.

**Comment by makermelissa** [comment]
Ok, it was merged and I just pushed a release. Please test at your convenience.

**Comment by makermelissa** [comment]
Sounds good. If you run into other issues, let’s open a new request.
