### ISSUE TITLE
Add _bleio support

### ISSUE THREAD

**Issue by rdagger** [adafruit/Adafruit_Blinka#163]
Any plans to add BLE support?  I’d like to be able to use CircuitPython BLE code to communicate between Raspberry Pi and nRF52840 Feather.

**Comment by ladyada** [comment]
no plans any time soon, bluez is completely different. you would want to try https://learn.adafruit.com/bluefruit-le-python-library instead!

**Comment by rdagger** [comment]
Thanks!  I tried Adafruit_Python_BluefruitLE but it appears to be broken with respect to the latest version of BlueZ that comes preloaded with Raspbian Buster.  I tried patching as recommended in https://github.com/adafruit/Adafruit_Python_BluefruitLE/issues/23 but it just wasn’t stable.

**Comment by ladyada** [comment]
yah that's not surprising, if you have any PR reviews or suggestions, let us know - bluez is kinda wretched :/
