### ISSUE TITLE
Add I2C baudrate to FT232H

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Blinka#174]
Worth adding? Think this just got overlooked.

Use `frequency` kwarg:
https://eblot.github.io/pyftdi/api/i2c.html#pyftdi.i2c.I2cController.configure
pass it through:
https://github.com/adafruit/Adafruit_Blinka/blob/8a4686cbc7ebd7f338f64517fa42db4dc5b5c78c/src/busio.py#L22
and use it here:
https://github.com/adafruit/Adafruit_Blinka/blob/8a4686cbc7ebd7f338f64517fa42db4dc5b5c78c/src/adafruit_blinka/microcontroller/ft232h/i2c.py#L9

**Comment by ladyada** [comment]
yep, for sure!

**Comment by caternuson** [comment]
I'll cycle back to this after MCP2221 work is finished.
