### ISSUE TITLE
Should I2C / SPI singletons be provided conditionally?

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_Blinka#186]
The I2C and SPI singletons are currently setup regardless of whether they exists or not:
https://github.com/adafruit/Adafruit_Blinka/blob/738d6d910c2dfa9763c3f33ddf4692c4823e136f/src/board.py#L109-L117
They would then show up in:
```python
>>> import board
>>> dir(board)
```
Python allows those functions to be defined even though the pin variables do not exists. It would then fail when called:
```python
>>> SPI = board.SPI()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "board.py", line 120, in SPI
    return busio.SPI(SCLK, MOSI, MISO)
NameError: name 'SCLK' is not defined
>>> 
```

Should they be provided conditionally? I'm thinking a simple check for the existence of SCL/SDA pins for I2C and SCLK/MOSI/MISO pins for SPI.

For bitbang, that would require explicit creation from the `bitbangio` module, so these singletons aren't used in that scenario. (i think?)

**Comment by makermelissa** [comment]
Sounds like a great idea. Also, we need some naming consistency because some boards have SCLK, some SCK, but I think most have both.
