### ISSUE TITLE
OneWire support in busio.py for Raspberry Pi

### ISSUE THREAD

**Issue by clex25** [adafruit/Adafruit_Blinka#198]
### Goal
I want to use a DS18B20 sensor on a Raspberry Pi 3B+ using the Adafruit OneWireBus library.

I have been following [this tutorial](https://learn.adafruit.com/using-ds18b20-temperature-sensor-with-circuitpython?view=all)

I'd like for the following code to work without error on the Pi3B+:

```
import board
from adafruit_onewire.bus import OneWireBus
ow_bus = OneWireBus(board.D7)
```

### Problem
Exact error: `AttributeError: module 'busio' has no attribute 'OneWire'`

Upon inspecting `busio.py`, I have noticed there is no OneWire class in that file. I have noticed that in circuit python there is a [`onewire.c` binding](https://github.com/adafruit/circuitpython/blob/master/shared-bindings/busio/OneWire.c).

### Troubleshooting performed
1. I have been successful at using the DS18B20 sensor using [this tutorial](https://learn.adafruit.com/adafruits-raspberry-pi-lesson-11-ds18b20-temperature-sensing/software) which accesses the device directly.
2. I'm reasonably confident that I have the `adafruit_blinka` library installed correctly, as I've done 2 successful tests with `adafruit_tsl2561` and `adafruit_bme280` libraries and gotten results from those sensors.
3. Just in case I missed something during install, or was out of date, I did reinstall as such:
```
 pip3 install --upgrade --force-reinstall adafruit-circuitpython-lis3dh
 pip3 install --upgrade --force-reinstall adafruit-blinka
```

### Open questions
1. Did I do something incorrect as far as installation, or missing files?
2. Is it even possible to support OneWire protocol here, or is there something specific to the timing of OneWire that would make it infeasible to implement in python directly?

If it's a matter of prioritization, I would consider opening a bounty for implementation, if feasible!

**Comment by ladyada** [comment]
pretty sure it isn't possible, there's no onewire exposure in the linux kernel - use the native kernel DS18b20 driver
