### ISSUE TITLE
Migrate to GithHub Actions

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_Blinka#217]
Let's get this over to GitHub actions; @siddacious, @sommersoft, or @dherrada can assist/review/do

**Comment by makermelissa** [comment]
First step will probably be linting...a lot...or we can do it after the migration and just not lint for now.

**Comment by makermelissa** [comment]
Ok, I noticed that it is already being linted, so I think this will be easier than I originally thought.

**Comment by makermelissa** [comment]
Oh, I did this already. Fixed via #276.
