### ISSUE TITLE
Python3.4 not compatible with pyftdi>=0.40.0

### ISSUE THREAD

**Issue by amrsoll** [adafruit/Adafruit_Blinka#249]
The [pyftdi] package requires python3.5 and up. This is a bummer for Raspbian/Debian Jessie that is stuck at python3.4 out-of-the-box.

### Request

Please consider to update setup.py with `'Programming Language :: Python :: 3.5'` instead of `Python :: 3.4` so as to not bring confusion.

### Reproduce problem

In a python3.4 venv on the Raspberry Pi 3B
```shell
python3.4 -m venv ~/myvenv
. ~/myvenv/bin/activate
pip install --upgrade-strategy=eager -U "pip<=18.0" # later pip versions require python 3.5
pip install -U setuptools
pip install adafruit-blinka
# No matching distribution found for pyftdi>=0.40.0 (from adafruit-blinka)
```

### Side note

Would it be possible to install adafruit without support for FTDI devices? Say if I only want to use the I2C bus on the Raspberry GPIO ?

### Mitigate problem for people in my situation

2 solutions:

- Compile the latest version of Python from scratch
- Use the stretch/main apt mirror to install python3.5 (What I did, but don't recommend for a stable OS)

To use the stretch Python3.5 precompiled python:

1. Add `deb http://mirrordirector.raspbian.org/raspbian/ stretch main` to `/etc/apt/sources.list`
2. Run this
```shell
sudo apt install python3.5 python3.5-venv
python3.5 -m venv ~/venv3.5/
. ~/venv3.5/bin/activate
pip install -U pip # might be unnecessary
pip install wheel # might be unnecessary
pip install adafruit-blinka
``` 

The install should be successful :smiley:

You can test your install with [a script](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi#blinka-test-3-15)

 I would probably recommend deleting the line added in `apt/sources.list` to prevent problems during an `apt update && apt upgrade`

[pyftdi]: https://pypi.org/project/pyftdi/0.40.5/

**Comment by makermelissa** [comment]
Excellent idea

**Comment by makermelissa** [comment]
I'm pretty sure the pyftdi was added as a requirement for using the Binho Nova and since it is meant to run on multiple platforms, we should leave this, which means we should go the route of requiring Python 3.5, which I believe is the version that CircuitPython is based off of anyways.
