### ISSUE TITLE
powershell set env var for adafruit ft232h

### ISSUE THREAD

**Issue by jsaksris** [adafruit/Adafruit_Blinka#252]
I have followed this tutorial 
https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/windows
but at the end import board gives me this error 
![image](https://user-images.githubusercontent.com/11375023/74659768-35a1e200-5195-11ea-9ece-d08c1d219247.png)

import usb seems fine
![image](https://user-images.githubusercontent.com/11375023/74660274-1c4d6580-5196-11ea-9533-ea9447acf603.png)

I'm working on Powershell with admin privilege.

Thank you for your help

**Comment by ladyada** [comment]
hi make sure you have done the environment variable setting

**Comment by jsaksris** [comment]
Works fine on cmd... should leave this open in case someone want to share how to set environment in powershell?

**Comment by ladyada** [comment]
please tell us how to do it and we'll add to the tutorial :) we dont use powershell :D

**Comment by makermelissa** [comment]
Oh yeah, I ran into this a month ago and just ended up using command. :) I'm definitely interested if you find a way to get it working.

**Comment by caternuson** [comment]
At powershell prompt, try: `$env:BLINKA_FT232H=1`

**Comment by makermelissa** [comment]
@caternuson, that worked. Want to add to your guide?

**Comment by caternuson** [comment]
@makermelissa sure thing, done:
https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/windows#set-environment-variable-3-30

**Comment by makermelissa** [comment]
Thanks
