### ISSUE TITLE
Is rotaryio missing?

### ISSUE THREAD

**Issue by mfeif** [adafruit/Adafruit_Blinka#261]
Hi there! I'm following the tutorial here: https://learn.adafruit.com/rotary-encoder/circuitpython

It says that rotaryio is built into CircuitPython from v4. I'm not able to import it on a rPi. I also can't find any 'rotaryio' stuff on PyPI.

Any pointers? Thanks!

**Comment by dhalbert** [comment]
That is right, there is not yet `rotaryio` support in blnka, sorry. In the native implementations, it is implemented with interrupts.
