### ISSUE TITLE
pylint is not being run on most files

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_Blinka#291]
`.github/workflows/build.yml` contains this pylint check:
```
- name: PyLint
      run: |
        pylint src/**/*.py
        ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name,bad-whitespace $( find . -path "./examples/*.py" ))
```

The `pylint src/**/*.py` is not actually matching most of the `.py` files, because `**` is not being interpreted by the shell running here as a wildcard match for multiple directories. (In `bash`, for instance, you have to turn on the `globstar` shell option to enable that.)

An alternative is to use `pylint $( find src -name '*.py' )` or something similar.

When this gets fixed, there will be a lot of pylinting to do :smile:, and `missing-docstrings` will have to get turned off, at least for now.

**Comment by makermelissa** [comment]
This wasn't as bas as the first time I went through all of the files and linted them. There were lots of duplicates. Also, I just added all the missing docstrings rather than turning off the check.
