### ISSUE TITLE
Bitbangio: ModuleNotFoundError: No module named 'machine'

### ISSUE THREAD

**Issue by tinue** [adafruit/Adafruit_Blinka#292]
I am trying to use BitBang on a Raspberry Pi 4. The module "bitbangio" references a module "machine" that I can't find. Is this an external dependency that needs to be installed first?

I see that there is a "# TODO untested" in the code, so maybe this does not work at the moment.

**Comment by makermelissa** [comment]
Hi, please try using https://github.com/adafruit/Adafruit_CircuitPython_BitbangIO. I'm going to leave this request open as a reminder to myself to update the message to hint to people to use that library.

**Comment by tinue** [comment]
Hello, thank you for the quick reply! Initial tests were partially successful, I am now getting "RuntimeError: First call try_lock()", but I'll experiment some more. I'm not expecting an answer here; This is another library after all ;-)
