### ISSUE TITLE
module 'board' has no attribute 'TX'

### ISSUE THREAD

**Issue by indramal** [adafruit/Adafruit_Blinka#303]
When I configure following line it gives me `module 'board' has no attribute 'TX'` error.

```
import board, busio
uart = busio.UART(board.TX, board.RX, baudrate=9600, timeout=10)
```

**Comment by indramal** [comment]
This is the reply for `dir(board)`

`['CE0', 'CE0_1', 'CE1', 'CE1_1', 'D10', 'D11', 'D12', 'D13', 'D16', 'D17', 'D18', 'D19', 'D20', 'D21', 'D22', 'D23', 'D24', 'D25', 'D26', 'D27', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'I2C', 'MISO', 'MISO_1', 'MOSI', 'MOSI_1', 'SCK', 'SCK_1', 'SCL', 'SCLK', 'SCLK_1', 'SCL_1', 'SDA', 'SDA_1', 'SPI', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'ap_board', 'board_id', 'detector', 'pin', 'sys']`

**Comment by jerryneedell** [comment]
What system are you running Blinka on?

**Comment by indramal** [comment]
Nvidia Jetson Nano

**Comment by jerryneedell** [comment]
hmmm -- sorry - I have no experience with that board. Hopefully someone else can help.

**Comment by indramal** [comment]
I found the solution. Thank you very much for helping me. 
I can not use this,
`uart = busio.UART(board.TX, board.RX, baudrate=9600, timeout=10)`
Instead I can use,
```
import serial
uart = serial.Serial("/dev/ttyUSB0", baudrate=9600, timeout=3000)
```

**Comment by CaptainJackey** [comment]
this should be fixed if we use circuitpython!!!
