### ISSUE TITLE
pyftdi.ftdi.FtdiError: UsbError: [Errno 16] Resource busy

### ISSUE THREAD

**Issue by glennford49** [adafruit/Adafruit_Blinka#312]
`import board`
`import digitalio as GPIO`
`pins = board.D7`
`pin1 = GPIO.DigitalInOut(pins)`
`pin1.direction = GPIO.Direction.OUTPUT# replaced INPUT in SECOND.py`
#FIRST.py and SECOND.py
i have 2 python script ,both has same variables and imports above, when i ran any of those py files it run smoothly but when i ran both at the same time the other one will throw this error : pyftdi.ftdi.FtdiError: UsbError: [Errno 16] Resource busy
the purpose of SECOND.py is to separately read pin state of which FIRST.py changes from False to True(HIGH to LOW)

**Comment by ladyada** [comment]
correct, you can only have one python running with an FTDI adapter - the script takes full control of the adapter!
