### ISSUE TITLE
set BLINKA_FT232H=1

### ISSUE THREAD

**Issue by versamodule** [adafruit/Adafruit_Blinka#315]
Can you please explain why we need to set this in the terminal before we use it? 
Why can this somehow be implemented in the code.  Seems to me this makes using Blinka useless if we want to send the code for someone else to try on their computer. 

Is there not another way in code do do this? 

Thanks

**Comment by caternuson** [comment]
It's how Blinka knows to look for the FT232H. You can set it in code if you want, but must do that before importing Blinka.
```python
import os
os.environ["BLINKA_FT232H"]="1"
import board
#etc
```

**Comment by versamodule** [comment]
Thank you so much!!!  That worked and was exactly what i was looking for.
