### ISSUE TITLE
AttributeError: module 'busio' has no attribute 'OneWire'

### ISSUE THREAD

**Issue by hkeown** [adafruit/Adafruit_Blinka#333]
Migrating to CircuitPython,  1-wire interface generates the following runtime error:
----------------------------------------------------------------------------------------------------
**Traceback:**

  ow_bus = OneWireBus(board.D2)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_onewire/bus.py", line 79, in __init__
    self._ow = busio.OneWire(pin)
AttributeError: module 'busio' has no attribute 'OneWire'

Process finished with exit code 1
----------------------------------------------------------------------------------------------------
**Test.py** 

import board
from adafruit_onewire.bus import OneWireBus
_ow_bus = OneWireBus(board.D2)_
devices = ow_bus.scan()

----------------------------------------------------------------------------------------------------
**Bus.py**

class OneWireBus:
    """A class to represent a 1-Wire bus."""

    def __init__(self, pin):
        # pylint: disable=no-member
        _self._ow = busio.OneWire(pin)_
        self._readbit = self._ow.read_bit
        self._writebit = self._ow.write_bit
        self._maximum_devices = _MAX_DEV

----------------------------------------------------------------------------------------------------
Package                          Version
-------------------------------- -----------
_Adafruit-Blinka                  5.3.0_
adafruit-circuitpython-ads1x15   2.2.2
adafruit-circuitpython-busdevice 5.0.1
adafruit-circuitpython-dht       3.5.0
_adafruit-circuitpython-ds18x20   1.3.1_
adafruit-circuitpython-lis3dh    5.1.2
adafruit-circuitpython-motor     3.2.1
adafruit-circuitpython-motorkit  1.5.2
_adafruit-circuitpython-onewire   1.2.2_
adafruit-circuitpython-pca9685   3.3.2
adafruit-circuitpython-register  1.9.0
adafruit-circuitpython-servokit  1.3.0
Adafruit-PlatformDetect          2.15.0
Adafruit-PureIO                  1.1.5

@caternuson

**Comment by hkeown** [comment]
Thank you for the prompt response @dhalbert , most appreciated.

I've been using https://github.com/timofurrer/w1thermsensor but wanted to port this to an Ada library. Is there any one in particular that you'd recommend?

**Comment by ladyada** [comment]
unlike i2c/spi/uart, we have not seen a low level one-wire kernel interface for arbitrary devices. thus circuitpython one wire libraries cannot be supported

**Comment by hkeown** [comment]
much appreciated @ladyada, seems like I'll have to stay with what I currently have...
