### ISSUE TITLE
Support for Nanopi Duo2

### ISSUE THREAD

**Issue by modi12jin** [adafruit/Adafruit_Blinka#350]
> It can be plugged into the breadboard, hoping to add its support.

![nanoPi](https://user-images.githubusercontent.com/40233017/95312245-44bed700-08c1-11eb-8110-b4e80d5e3542.jpg)

![nanopi_duo2](https://user-images.githubusercontent.com/40233017/95312299-56a07a00-08c1-11eb-9b00-1e43cf2c41a0.jpg)

**Comment by modi12jin** [comment]
![mmexport1609417404617](https://user-images.githubusercontent.com/40233017/103410463-3f161c00-4ba6-11eb-9c4e-162b1b882b5b.jpg)

 > I have completed the first part

**Comment by modi12jin** [comment]
![IMG_20210102_163731](https://user-images.githubusercontent.com/40233017/103454059-0f3c5500-4d1b-11eb-85ff-803c146c01fe.jpg)

> circuitPython for nanopi duo2

**Comment by ladyada** [comment]
awesome, that looks great! please submit PR for platformdetect and blinka support :)

**Comment by ladyada** [comment]
@modi12jin will you be sending a PR?

**Comment by modi12jin** [comment]
@ladyada I posted a request, why did it fail?
I'm a novice and don't know where is the problem
