### ISSUE TITLE
Add Banana Pi M2 Zero

### ISSUE THREAD

**Issue by twa127** [adafruit/Adafruit_Blinka#357]
Hi,

I'd like to add support for the Banana Pi M2 Zero, but can't see where to add the changes required in /usr/local/lib/python3.7/dist-packages/adafruit_platformdetect/constants/boards.py

**Comment by ladyada** [comment]
please start here 
https://learn.adafruit.com/adding-a-single-board-computer-to-platformdetect-for-blinka

**Comment by makermelissa** [comment]
Closed via #358
