### ISSUE TITLE
Allwinner H3 GPIO PL2 and PL4

### ISSUE THREAD

**Issue by twa127** [adafruit/Adafruit_Blinka#361]
Hi

Can we please add GPIO pins PL2 and PL4 to the allwinner H3 to support the BananaPi M2 Zero

**Comment by makermelissa** [comment]
Sure. Go ahead and add it if you know the pin number. My guess would be Pin(226) and Pin (228) based on there being 32 pins per letter and PL being right after PG in the Data sheet pins, but that's just a guess.

**Comment by twa127** [comment]
Hi,

Turned out to be Pin((1, 2)) and Pin((1, 4)), added to my last commit, hope that's okay

**Comment by makermelissa** [comment]
That's fine. Thanks.

**Comment by makermelissa** [comment]
Fixed by #360.
