### ISSUE TITLE
Update README.md to emphasize CPython support

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_Blinka#369]
The very first sentence in README.md is:
>This repository contains a selection of packages mirroring the CircuitPython API on hosts running micropython.

MicroPython and CPython are mentioned together more later, but the README could probably use an updating to emphasize the current goals, which are more about CPython.

(Is the MicroPython support still viable?)

**Comment by makermelissa** [comment]
As far as I've heard MicroPython support is still viable. I know there was an issue at one point and somebody let us know and it was fixed. I haven't heard of it not working since.

**Comment by ladyada** [comment]
i want to maintain micropython support - micropython community needs drivers, and especially with the new microbit this is a good solution.

**Comment by jerryneedell** [comment]
I have had very little success with Micropython. I may be doing it wrong. How do you use it with Micropython? What BSPs work?

**Comment by ladyada** [comment]
yeah it does not work in micropython right now

**Comment by dhalbert** [comment]
I'll make a separate issue for that now.
