### ISSUE TITLE
Add PWMOut to RasPi Blinka

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_Blinka#37]
Using the RPi.GPIO library (https://github.com/adafruit/Adafruit_Blinka/blob/master/src/adafruit_blinka/microcontroller/raspi_23/pin.py#L1), we could add PWM functionality similar to PWMOut (https://circuitpython.readthedocs.io/en/2.x/shared-bindings/pulseio/PWMOut.html)  for the Raspberry Pi.

Initialization:
```
pwm = GPIO.PWM(pin, frequency)
pwm.start(duty_cycle) 
```

`variable_frequency` -> `ChangeFrequency`
`ChangeDutyCycle` -> `duty_cycle`

- example of the RPi.GPIO PWM https://sourceforge.net/p/raspberry-gpio-python/wiki/PWM/

**Comment by ladyada** [comment]
i did this but for sysfs pwm only - not 'soft' PWM like gpiozero does. still, its nice on boards that have hardware PWM!

**Comment by makermelissa** [comment]
This would be handy for displayio backlights.

**Comment by ladyada** [comment]
@makermelissa its non trivial, please use backlight on/off for now

**Comment by makermelissa** [comment]
Yeah, that's what I'm doing. :)
