### ISSUE TITLE
using the library with raspberry pi

### ISSUE THREAD

**Issue by TheLamia** [adafruit/Adafruit_Blinka#375]
I am facing issues running the library on raspberry pi, as I keep getting an error for the correct pins (12,19,13) or even non PWM channels  (5,6,7) for R,G,B leds.

> TypeError: Must provide a pin, PWMOut, or PWMChannel.

In the code, this error is raised in the case which pin does not have the frequency attribute, or its type is not <class 'Pin'>. 
when I tried modifying the code I find the following type for the pins 

> <class 'adafruit_blinka.microcontroller.bcm283x.pin.Pin'>

**Comment by makermelissa** [comment]
Please verify you are using the Broadcom Pin numbers (GPIOs) and not the physical pin numbers. Here's a useful diagram: https://pinout.xyz/

**Comment by makermelissa** [comment]
Closing due to lack of a response. If this is still an issue, feel free to re-open.
