### ISSUE TITLE
Pi to control circuit playground express

### ISSUE THREAD

**Issue by genus1** [adafruit/Adafruit_Blinka#39]
It would be nice to see some example code of raspberry pi interfacing with circuit playground express.

I really like what you guys do at adafruit.  I am building a full AI robot using the raspberry pi for all the heavy stuff like speech and image recognition, files ect and I plan on using several circuit playground express for lots of sensor input and specific control.  I am using an arduino for motor control, and general movement decisions.  Circuitpython looks like the way to make it all work together.

I have not done it yet but it looks like with circuitpython on the pi I should be able to communicate and control the arduino and circuit playground express via ic2 instead of my original usb approach.

**Comment by ladyada** [comment]
gotch'er guide on that right here!
https://learn.adafruit.com/circuit-playground-express-serial-communications
