### ISSUE TITLE
Compatibility list?

### ISSUE THREAD

**Issue by rpavlik** [adafruit/Adafruit_Blinka#399]
Is there any interest in a compatibility list, especially for things like the MCP2221 where its behavior is not necessarily the same as e.g. samd21? Just tried out my EMC2101 with the MCP2221 and it happily worked first try. (Even my 12V fan worked powered from the 5V USB supply once I "started it" by hand)

Or, should I just stick to reporting the exceptions where it doesn't work?

**Comment by ladyada** [comment]
plz report exceptions, things should work as is. :)
