### ISSUE TITLE
Add pulseio.PulseIn support

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_Blinka#41]
I can be bitbanged in a separate thread or process. Bitbanging code is here:
 
https://github.com/adafruit/Adafruit_CircuitPython_DHT/pull/18

**Comment by ladyada** [comment]
this is almost done using libgpiod

**Comment by makermelissa** [comment]
This is in place, but as stated in the previous comment, more boards (at least ones with libgpiod support) will need testing and putting in place.

**Comment by makermelissa** [comment]
Fixed via #506 and #593. The pulsein library is included and the appropriate file is automatically detected and loaded.
