### ISSUE TITLE
MCP2221: I2C write error: max retries reached

### ISSUE THREAD

**Issue by chocer** [adafruit/Adafruit_Blinka#419]
I refer to the mcp2221.py in my project.when i use it for i2c read or write,sometimes it raise the error:"I2C write error, max retries reached." then i read the I2C state ,value is 0x43. In thie file , it deficed as RESP_I2C_MOREDATA. so what's the meaning of "RESP_I2C_MOREDATA"?  I really need to know it to slove the bug

**Comment by caternuson** [comment]
What is the I2C device being talked to?

**Comment by caternuson** [comment]
Closing due to lack of response. Can reopen if more information provided.
