### ISSUE TITLE
requirements should also install rpi_ws281x on pi zero

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_Blinka#45]
i think a pi zero is an armv6 or something? lets make it auto install on a pi zero too

> Someone on discord was following this guide using a Pi Zero W:
> https://learn.adafruit.com/neopixels-on-raspberry-pi
> It didn't work because rpi_ws281x didn't get installed along with blinka. Probably because of this:
> https://github.com/adafruit/Adafruit_Blinka/blob/master/requirements.txt#L2
> They did a manual pip3 install of rpi_ws281x and their NeoPixels started working.
> 
> This is probably a similar issue:
> https://forums.adafruit.com/viewtopic.php?f=50&t=143702
> although Pi model is unknown at this point.

**Comment by brennen** [comment]
yeah, i started looking into this a bit ago, and somewhat relatedly need to finish up a tweak to platform detection in Adafruit_Python_GPIO:

https://github.com/adafruit/Adafruit_Python_GPIO/compare/platform_detect_pi_zero
