### ISSUE TITLE
Allwinner H6 pin.py

### ISSUE THREAD

**Issue by twa127** [adafruit/Adafruit_Blinka#453]
Hi,

I think there may be an error in pin.py for the Allwinner H6, GPIO PL8 and PL9 are set as

PL8 = Pin((1, 360))
PL9 = Pin((1, 361))

The H6 appears to have 256 lines on GPIO Controller1, testing on my PineH64-B, I think the definition should be

PL8 = Pin((0, 8))
PL9 = Pin((0, 9))

**Comment by makermelissa** [comment]
I think you're right. The AllWinner A64 also uses the same pin. Want to submit a PR?

**Comment by makermelissa** [comment]
Fixed via #456
