### ISSUE TITLE
busio I2C import on RPi

### ISSUE THREAD

**Issue by magnus-haw** [adafruit/Adafruit_Blinka#49]
Line 21 in busio.py should have an "elif" statement instead of an "if" statement. Currently, if the board is not a beaglebone_black, the code attempts to execute the last else statement. This creates an error for Raspberry pi boards which do not use the Micropython machine module.

Discovered this issue when trying to install CircuitPython from this tutorial: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi

def init(self, scl, sda, frequency):
        self.deinit()
        **if** board_id == "raspi_3" or board_id == "raspi_2":
            from adafruit_blinka.microcontroller.raspi_23.i2c import I2C as _I2C
        **if** board_id == "beaglebone_black":
            from adafruit_blinka.microcontroller.raspi_23.i2c import I2C as _I2C
        **else**:
            from machine import I2C as _I2C

->>>
def init(self, scl, sda, frequency):
        self.deinit()
        **if** board_id == "raspi_3" or board_id == "raspi_2":
            from adafruit_blinka.microcontroller.raspi_23.i2c import I2C as _I2C
        **elif** board_id == "beaglebone_black":
            from adafruit_blinka.microcontroller.raspi_23.i2c import I2C as _I2C
        **else**:
            from machine import I2C as _I2C

**Comment by gjoseph** [comment]
Found the same thing @magnus-haw - here's a PR that I hope will get merged soon :)

**Comment by asidroid** [comment]
@magnus-haw Thanks!

**Comment by ladyada** [comment]
we're about to fix this with a different PR, hold tight!

**Comment by ladyada** [comment]
apologies for the break. lots of dev goin' on 
please try 0.3.1 - i tested it but it could use more testin' as always :)

**Comment by csylvain** [comment]
that (0.3.1) broke something (0.3.0 worked after changing that one "if" to "elif")
Traceback (most recent call last):
  File "bme280_simpletest.py", line 8, in <module>
    i2c = busio.I2C(board.SCL, board.SDA)
  File "/home/pi/.local/lib/python3.5/site-packages/busio.py", line 15, in __init__
    self.init(scl, sda, frequency)
  File "/home/pi/.local/lib/python3.5/site-packages/busio.py", line 20, in init
    from adafruit_blinka.microcontroller.generic_linux.i2c import I2C as _I2C
ImportError: No module named 'adafruit_blinka.microcontroller.generic_linux'

**Comment by ladyada** [comment]
hmm - lemme take another look

**Comment by ladyada** [comment]
OK please try 0.3.2!

**Comment by ladyada** [comment]
i think this is resolved now, @brennen  tested it. closing - please reopen if it's still an issue

**Comment by csylvain** [comment]
no pin.py in generic_linux ? only in raspi_23.

**Comment by ladyada** [comment]
thats correct, we have not done our libgpiod changes so pin control is still board specific

**Comment by csylvain** [comment]
k!
