### ISSUE TITLE
misleading docstr in DigitalInOut.pull

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/Adafruit_Blinka#499]
https://github.com/adafruit/Adafruit_Blinka/blob/4f4e6af0a2c2912d7662f0160849806507b125bd/src/digitalio.py#L190-L191

I think this docstr should say
```py
"""Get or set the Digital Pin's input impedance."""
```

ps - I think this is simply a copy-n-paste mistake.

**Comment by makermelissa** [comment]
Possibly. It's been there longer than I've been working on this project.

**Comment by tannewt** [comment]
Property documentation shouldn't say `get or set` that is implied. The CircuitPython doc string for this is `The pin pull direction.` https://github.com/adafruit/circuitpython/blob/main/shared-bindings/digitalio/DigitalInOut.c#L306

**Comment by makermelissa** [comment]
It should probably be updated to `"""Get or Set the Digital Pin Pull Direction"""`

**Comment by 2bndy5** [comment]
@tannewt is right. The "get or set" not being needed is a  stipulation actually noted in the CirPy contribution guide. I was just guessing with my first suggestion.

**Comment by makermelissa** [comment]
Oh I see, I've probably made that mistake in other libraries myself.
