### ISSUE TITLE
Missing GPIO pin definition for rockpi4

### ISSUE THREAD

**Issue by A-Zoomer** [adafruit/Adafruit_Blinka#530]
Referencing file: 
`./src/adafruit_blinka/board/radxa/rockpi4.py`

When i was mapping pins for a rock3a (and taking the mentioned file as example), i noticed the pin 12 is missing from the GPIO definitions. 
More precisely: `D12 = GPIO4_A3` with I2S1_SLCK (n. 131) is missing.

**Comment by makermelissa** [comment]
Closing as it appears to have been added at some point.
