### ISSUE TITLE
Pi RGBW NeoPixel support incomplete?

### ISSUE THREAD

**Issue by waded** [adafruit/Adafruit_Blinka#56]
I was working through https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage, adding https://learn.adafruit.com/circuitpython-essentials/circuitpython-neopix to understand how to add the W component (using bpp=4), with a Raspberry Pi Zero W and the RGBW Neopixel strip.

It didn't seem to work correctly. The result of this script:

```
import board
import neopixel
pixels = neopixel.NeoPixel(board.D18, 20, bpp=4, auto_write=False)
pixels.fill((255, 0, 0, 0))
pixels.write()
```

was a repeating pattern of red, blue, unlit, green down the strip. I expected them to all be red (or at least all the same color.)

I took a look at the code and eventually got to 1f9263a050a781740d3fda52a632048b64912971, which implies RGBW is supported, but it didn't appear the W bits were being shifted in for the call to `ws.ws2811_led_set`, which would explain the behavior I saw.

**Comment by waded** [comment]
@ladyada Unfortunately I don't have any RGBs to test. I'll edit issue to add example code and the resulting color sequence here in a sec.

**Comment by waded** [comment]
I will add that I did try rpi_ws281x's Python examples, notably SK6812_strandtest.py, which does solid color fills, including white, and that was working as expected.

**Comment by ladyada** [comment]
oh ok you know i know what happened, i can fix it

**Comment by caternuson** [comment]
does this need updating to sync up with latest RGBW tweaks?
https://github.com/adafruit/Adafruit_Blinka/blob/master/src/adafruit_blinka/microcontroller/raspi_23/neopixel.py#L71

**Comment by ladyada** [comment]
no i think its just the way the raspi neopixel driver expects data, if i set it to RGBW i think i have to shift data in differently. im getting an RGBW ring to do a proper test

**Comment by waded** [comment]
I'd be happy to test a fix on my strip when you have one. I prototyped a fix (changed the ` # assign all colors!` block to also be based on `LED_STRIP` and shift the w value into `pixel` in the RGBW case), but I don't have a way to test anything but.

**Comment by ladyada** [comment]
i believe its now fixed in a PR
