### ISSUE TITLE
ImportError: no module named 'typing'

### ISSUE THREAD

**Issue by Michel-HEG** [adafruit/Adafruit_Blinka#570]
with my raspberrypi pico i have this error, is there a way to have this module??

**Comment by dhalbert** [comment]
This module is not meant for use on the Pi Pico. What code is throwing this error? In our libraries, we usually do something like:
```py
try:
    from typing import ...   # some things
except ImportError:
    pass
```

**Comment by Michel-HEG** [comment]
i'm trying to use HID and that module imports that, i have this error:

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/lib/usb_hid.py", line 14, in <module>
ImportError: no module named 'typing'
>>>

**Comment by Michel-HEG** [comment]
yes i'm doing that, i will check your link thanks

**Comment by Michel-HEG** [comment]
i used try catch: but it doesn't work, i have the same error with evry other modules below now:
`>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/lib/usb_hid.py", line 19, in <module>
ImportError: no module named 'pathlib'
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 22, in <module>
ImportError: no module named 'atexit'
>>> `

**Comment by DanielTomlinsonSage** [comment]
usb_hid.py no longer exists! No alternative given, same general issue.

**Comment by makermelissa** [comment]
> usb_hid.py no longer exists! No alternative given, same general issue.

Do you mean this file? https://github.com/adafruit/Adafruit_Blinka/blob/main/src/usb_hid.py

**Comment by makermelissa** [comment]
`usb_hid.py` was recently added by a community member to make use of the usb_gadget driver, which is only on linux. I'm not sure what it would take to make use of something similar within MicroPython.

**Comment by makermelissa** [comment]
Fixed via https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/230 and #586.
