### ISSUE TITLE
Blinka does not install adafruit-circuitpython-typing

### ISSUE THREAD

**Issue by tekktrik** [adafruit/Adafruit_Blinka#580]
Release 7.0.0 sounds like it made it so `adafruit-circuitpython-typing` but it wasn't added to `setup.py` or `requirements.txt`.  I think a lot of the libraries (at least the ones I've seen/modified) explicitly call out for that module in their own `setup.py` and `requirements.txt`, so it hasn't been a huge issue.  Should it be added here and automatically installed with Blinka, or only installed once a package is installed that makes use of those types?

**Comment by makermelissa** [comment]
Yes please install with Blinka. Good call.
