### ISSUE TITLE
RockPi 3A is not suport.

### ISSUE THREAD

**Issue by hurricane88888** [adafruit/Adafruit_Blinka#595]
RockPi 3A is not suport.hopeful suport

**Comment by thecalle** [comment]
I got a RockPi 3A. Help needed?

**Comment by makermelissa** [comment]
Yes please. Here are the guides that go over how to add to Blinka:
https://learn.adafruit.com/adding-a-single-board-computer-to-platformdetect-for-blinka
https://learn.adafruit.com/adding-a-single-board-computer-to-blinka

**Comment by Handonghuang** [comment]
> I got a RockPi 3A. Help needed?

How is it going? I really need help.

**Comment by makermelissa** [comment]
Fixed via #649.
