### ISSUE TITLE
There is a installation tutorial or wheel for Rapberry Pi 4 with Ubuntu 22.04?

### ISSUE THREAD

**Issue by FPSychotic** [adafruit/Adafruit_Blinka#604]
I followed the official guide of RPi4 but it finally ask by RaspiOS and followed the tutorial "build circuitpython" and I think did right choosing the arm runtime but it failed when compiled like could not find the runtime, not sure if I miss on which, I could not understand very well some steps, was confusing understand what part is RPi4 and which X86 probably due to my bad english.

Do you know if it is possible install in 22.04 with any procedure?

**Comment by makermelissa** [comment]
Hi, we don't have a guide or support for ubuntu, but I've heard of a few folks installing it successfully somehow. I can't remember which version they used, but I think it was 22.04.
