### ISSUE TITLE
adafruit_hid on raspberry pi zero

### ISSUE THREAD

**Issue by Med-JH** [adafruit/Adafruit_Blinka#607]
Hi,

I am trying to use HID emulation with a rasperry pi zero 2w and keep running into issues.

I already opened a thread [on adafruit forums](https://forums.adafruit.com/viewtopic.php?p=939553#p939553) but was referred here.

The system is prepared:
OS: 2022-04-04-raspios-bullseye-arm64-lite.img.xz

1. apt update and upgrade
2. installed circuit by [following](https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi)
3. pip3 install adafruit-circuitpython-hid
4. add to dtoverlay=dwc2 to /boot/config.txt and reboot.
5. sudo modprobe libcomposite

First issue:

TLDR: usb_hid.py, line 63 " encoding="utf-8"" seems breaks functionality

running the following script with _sudo python_  gives the following output

```
import usb_hid
from adafruit_hid.keyboard import Keyboard
from adafruit_hid.keycode import Keycode
usb_hid.enable((usb_hid.Device.KEYBOARD,))
kbd = Keyboard(usb_hid.devices)

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/root/.local/lib/python3.9/site-packages/adafruit_hid/keyboard.py", line 68, in __init__
self.release_all()
File "/root/.local/lib/python3.9/site-packages/adafruit_hid/keyboard.py", line 119, in release_all
self._keyboard_device.send_report(self.report)
File "/usr/local/lib/python3.9/dist-packages/usb_hid.py", line 66, in send_report
fd.write(report)
TypeError: write() argument must be str, not bytearray
```
as suggeted in the linked thread changing line 63 from
`with open(device_path, "rb+", encoding="utf-8") as fd:`
to
`with open(device_path, "rb+",) as fd:
`
allows keyboard emulation

**Comment by makermelissa** [comment]
Fixed via #606
