### ISSUE TITLE
I was using rev 1.4 and had no problems but recently bought some new 4b raspberry pi and I guess its 1.5 and now my clone os is throwing this error.

### ISSUE THREAD

**Issue by nolansingroy** [adafruit/Adafruit_Blinka#622]
I was using rev 1.4 and had no problems but recently bought some new 4b raspberry pi and I guess its 1.5 and now my clone os is throwing this error. 
![image](https://user-images.githubusercontent.com/5677688/196077930-c43cc2eb-3a61-4bfa-85d3-6bd4b4435be6.png)

cat /proc/cpuinfo
![image](https://user-images.githubusercontent.com/5677688/196077866-d83c31d1-9727-4272-b77e-2e9eb561788c.png)

  
 My cloned os using the adafruit plugin for neopixel was working on this version of raspberry pi 
Hardware	: BCM2711
Revision	: c03114
Serial		: 100000005a9870db
Model		: Raspberry Pi 4 Model B Rev 1.4
 

 **Please any advice or help would be greatly appreciated!**

__Originally posted by @nolansingroy in https://github.com/adafruit/Adafruit_Blinka/issues/66#issuecomment-1280200150__

**Comment by makermelissa** [comment]
Feel free to re-open this if that doesn't solve the issue.

**Comment by nolansingroy** [comment]
@makermelissa the above was installed and it stopped saying board not support however when I run the adafruit blinka neopixel code I get 
![image](https://user-images.githubusercontent.com/5677688/198384638-b71ae107-671d-41f1-986d-2859e37b3ec5.png)
