### ISSUE TITLE
ModuleNotFoundError: No module named 'board'

### ISSUE THREAD

**Issue by hbarnard** [adafruit/Adafruit_Blinka#640]
Followed instructions for raspi-blinka.py and more recently setup.py install here. But after reinstall of OS on Pi4: https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit my Python project cannot find board.
And yes I've made sure that the 'other' board is not installed.

It looks as though:
```
sudo pip3 install rpi_ws281x adafruit-circuitpython-neopixel
sudo python3 -m pip install --force-reinstall adafruit-blinka
```
_may_ solve this but I'm not sure what else it may affect in the project?

**Comment by caternuson** [comment]
The suggested fix is here:
https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/faq-troubleshooting#faq-3055911

**Comment by hbarnard** [comment]
> The suggested fix is here: https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/faq-troubleshooting#faq-3055911

Thanks, my comment above, seems to have fixed it. However, I'm heading away from the voice bonnet because of the library complexity.
