### ISSUE TITLE
Blinka referencing sysfs_pin.py and not libgpiod_pin.py

### ISSUE THREAD

**Issue by Gerriko** [adafruit/Adafruit_Blinka#676]
I am using a Rock4 C+ board and I am developing my own SPI library.

For some reason I am getting an error:
`adafruit_blinka.microcontroller.generic_linux.sysfs_pin.GPIOError: [Errno 22] Unexporting GPIO: Invalid argument`

What I cannot work out is why is Blinka using sysfs_pin.py when it should really be using libgpiod_pin.py

PS. (EDIT)

I assume this is kernel version related. As Radxa have very recently released a new Debian and Ubuntu versions we should now be using libgpiod_pin.

Maybe some sort of check or setting that allows the user to select an option is needed (@MathijsNL).

**Comment by Gerriko** [comment]
In order to use libgpiod library with the rk3399, I discovered that the GPIO pin definitions found in the rk3588 pin.py file are perfectly suited here too (as a replacement): 
https://github.com/adafruit/Adafruit_Blinka/blob/main/src/adafruit_blinka/microcontroller/rockchip/rk3588/pin.py

**Comment by Gerriko** [comment]
@makermelissa I am wondering if there is a way to handle both sysfs_pin and libgpiod_pin inside the microcontroller pin.py file.

I have a similar issue with the Rock CM3 board, but this time in reverse, where the official (and working) Radxa distro release is still using sysfs_pin. However, most other boards, which also use the RK3566 chip, will be using libgpiod_pin.

Can PlatformDetect be used here?

What other options are possible to allow for both use cases?

**Comment by makermelissa** [comment]
Perhaps you have have 2 versions of the RK3566 with it specified as libgpiod or sysfs. So maybe it would be something like `rk3566_sysfs/` and `rk3566_libgpiod/`. Then you can point the board to the appropriate one.

**Comment by makermelissa** [comment]
Or better yet, maybe create `sysfs` and `libgpiod` folders inside of the `rk3566` folder.

**Comment by makermelissa** [comment]
Fixed via #677.
