### ISSUE TITLE
pwmio support for Jetson Nano

### ISSUE THREAD

**Issue by lsaltz** [adafruit/Adafruit_Blinka#679]
I am using a Jetson Nano Dev Kit, and am trying to run Adafruit's MotorKit library on it. I am unable to import the library as it says:
```
pwmio not supported for this board.
```
I traced it back to the Blinka library code and found that the Jetson Nano is not supported by pwmio. Is adding this support possible?

**Comment by makermelissa** [comment]
Hi,

This is similar to #471, where it sounds like it might be possible. If you would like to try and get it working, please submit a PR. Thanks!

**Comment by makermelissa** [comment]
I wonder if rpi-lgpio would work...
