### ISSUE TITLE
Latest version doesn't work on rp2040 pico due to a pin/digitalio error.

### ISSUE THREAD

**Issue by ryanayoung** [adafruit/Adafruit_Blinka#729]
### Board Name

rp2040 pico

### Steps

Follow Blinka and Platformdetect installation steps as described in adafruit tutorial. 

1. Install micropython on rp2040 pico
2. Copy contents of Adafruit_Blinka/src into /lib folder of rp2040
3. Copy adafruit_platformdetct into /lib folder of rp2040
4. Create a circuit python blink project that uses digitalio, i.e. `led = digitalio.DigitalInOut(board.GP25)`
5. run project
*instructions pulled from adafruit tutorial. https://learn.adafruit.com/circuitpython-libraries-on-micropython-using-the-raspberry-pi-pico/installing-blinka-and-libraries

Expected result: Led blinks.

Actual results: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/board.py", line 37, in <module>
  File "/lib/adafruit_blinka/board/raspberrypi/pico.py", line 6, in <module>
  File "/lib/adafruit_blinka/microcontroller/rp2040/pin.py", line 6, in <module>
ImportError: no module named 'adafruit_blinka.microcontroller.generic_micropython'
```

### Description

the specific library it calls in /lib/adafruit_blinka/microcontroller/rp2040/pin.py has the line `from ..generic_micropython import Pin` but I can't find anything about this ..generic_micropython line.

### Additional information

I rolled back to version 6.9.1, which the line in pin.py is `from microcontroller import Pin` and it works.
Unfortunately just changing that line in the latest version back to 'microcontroller' doesn't solve the problem, so it seems to be something deeper. 
The change was made in commit [1b0f8f8](https://github.com/adafruit/Adafruit_Blinka/commit/1b0f8f8ec96aadfb7fd106677f3b5b0be24cec85)

**Comment by makermelissa** [comment]
You will also need the https://github.com/adafruit/Adafruit_Blinka/tree/main/src/adafruit_blinka/microcontroller/generic_micropython folder. Closing because I've updated the guide to reflect that.
