### ISSUE TITLE
MCP2221A import board error issue

### ISSUE THREAD

**Issue by thinphone23** [adafruit/Adafruit_Blinka#731]
### Board Name

MCP2221 usb

### Steps

code from user guideCircuitPython Libraries on any Computerwith MCP2221.pdf

import time
import board
import digitalio
led = digitalio.DigitalInOut(board.G0)
led.direction = digitalio.Direction.OUTPUT
while True:
    led.value = True
    time.sleep(0.5)
    led.value = False
    time.sleep(0.5)

### Description

![image](https://github.com/adafruit/Adafruit_Blinka/assets/11549435/a5b0ce05-719d-42cd-9650-e4d274aac909)

### Additional information

![image](https://github.com/adafruit/Adafruit_Blinka/assets/11549435/d7f9a8ec-d998-461e-af07-83b05595e942)

**Comment by makermelissa** [comment]
If you need further assistance setting it up, you can either use the Support forums at  https://forums.adafruit.com or the Adafruit Discord at http://adafru.it/discord.
