### ISSUE TITLE
Arduino Uno

### ISSUE THREAD

**Issue by shahad2802** [adafruit/Adafruit_Blinka#744]
i was trying to import board library to combine between arduino and python but it keeps sending errors and tell me maybe my board not supported yet :(

**Comment by makermelissa** [comment]
If you are referring to Arduino Uno R3 or earlier, it uses an atmega328, which is not powerful enough. If you meant the Arduino Uno R4, you are correct in that it isn't supported yet.

**Comment by shahad2802** [comment]
I think mine is R3, is it work on it?

**Comment by makermelissa** [comment]
Blinka won't work on the R3. It is not powerful enough.

**Comment by makermelissa** [comment]
It looks like there isn't enough flash memory to work on the R4 either. It barely fit on the pico with 2MB and the R4 only has 256KB.
