### ISSUE TITLE
RP2040 fails on valid UART pin combinations

### ISSUE THREAD

**Issue by shawnferry** [adafruit/Adafruit_Blinka#759]
### Board Name

rp2040 on custom PCB

### Steps

Define UART on valid pins

![image](https://github.com/adafruit/Adafruit_Blinka/assets/485104/b6e01f5e-128e-4eda-9160-903b703dec7a)

```
busio.UART(board.GP16, board.GP17)
```

```
E   ValueError: No Hardware UART on (tx,rx)=(16, 17)
E   Valid UART ports: ((0, board.GP0, board.GP1), (0, board.GP0, board.GP13), (0, board.GP12, board.GP1), (0, board.GP12, board.GP13), (1, board.GP4, board.GP5), (1, board.GP4, board.GP9), (1, board.GP8, board.GP5), (1, board.GP8, board.GP9))
```

### Additional information

Pull request incoming

**Comment by makermelissa** [comment]
It sounds like you are running it as one of the U2IF boards. What board definition are you using?

**Comment by makermelissa** [comment]
Never mind, looks like you already figured out the issue and submitted #760.
