### ISSUE TITLE
Support for Feather M4 Express

### ISSUE THREAD

**Issue by Jwyatt0911** [adafruit/Adafruit_Blinka#768]
Arduino IDE and Visual Studio Code both fail to detect my Feather M4 Express with a Feather JoyWing. Already tried updating, so I assume my board isn't supported. No matching boards show up in the Arduino IDE either. Upon running, I was told to create a new issue.
![image](https://github.com/adafruit/Adafruit_Blinka/assets/103787850/8e1ebeeb-7424-4a28-a453-d82759b72f53)

**Comment by makermelissa** [comment]
You are correct in that board not being supported by Blinka, nor are there plans to add it. Blinka mostly runs on linux boards, and in some cases on top of MicroPython, and in other cases through a special proxy firmware.

It sounds like you may want CircuitPython though. Here's a guide for getting started with installing it: https://learn.adafruit.com/welcome-to-circuitpython/installing-circuitpython
