### ISSUE TITLE
UnexpectedMakers ProS3

### ISSUE THREAD

**Issue by kraakula** [adafruit/Adafruit_Blinka#780]
Hello 

Can you add support for the ESP32-S3?

https://circuitpython.org/board/unexpectedmaker_pros3/

**Comment by makermelissa** [comment]
Possibly. Why not just run CircuitPython though?

**Comment by kraakula** [comment]
i made a mistake, i was trying to use vs code and the extension for CircuitPython and it pointed to the wrong board.py. thanks for replying

**Comment by makermelissa** [comment]
Ah, fair enough. :)
