### ISSUE TITLE
Please support RP2040-LCD-1.28

### ISSUE THREAD

**Issue by nickmaleki** [adafruit/Adafruit_Blinka#788]
Hello, I recently purchased https://www.waveshare.com/wiki/RP2040-LCD-1.28 and I am able to get gyro information from the device in CircuitPython, but when I go to use the adafruit-blinka package in my usual python environment, I get the following error: 
```
 import board
    raise NotImplementedError(
NotImplementedError: 
        Adafruit-PlatformDetect version 3.60.0 was unable to identify the board and/or
        microcontroller running the Windows platform.
```
I am unfortunately unable to use the socket library to retrieve the data from circuit python and have yet to find a work around, so if this library was updated to support this board, that would be great, thank you.

**Comment by makermelissa** [comment]
There aren't many instances where this library runs on the host computer. There are a handful of boards that you can use it to interact with the GPIO on. It sounds more like you only need to retrieve data. You may want to check out this guide that I wrote where I'm doing just that: https://learn.adafruit.com/macropad-remote-procedure-calls-over-usb-to-control-home-assistant
