### ISSUE TITLE
adafruit

### ISSUE THREAD

**Issue by quicassilva** [adafruit/Adafruit_Blinka#789]
Não consigo instalar a biblioteca adafruit no meu windows

**Comment by dhalbert** [comment]
> Não consigo instalar a biblioteca adafruit no meu windows

"I can't install the adafruit library on my windows"

Please use the "Bug Report" template: https://github.com/adafruit/Adafruit_Blinka/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml and refile this issue.

**Comment by makermelissa** [comment]
I assume you're referring to this library. I would need more information such as error messages and which board you are trying to use it with.
