### ISSUE TITLE
These are very inexpensive and I think would be good boards to support -- LuckyFox Pico Mini

### ISSUE THREAD

**Issue by earlthesquirrel** [adafruit/Adafruit_Blinka#796]
https://www.spotpear.com/index/product/detail/id/1413.html Is a link to the board.
They are nice small boards that have a nice CPU and a fair number of GPIO and camera interface.

Would love to be able to use them with Circuit Python

EDIT by @dhalbert: https://www.luckfox.com/Luckfox-Pico

**Comment by makermelissa** [comment]
Oh nice! Yes, these would be great to add.

**Comment by nopnop2002** [comment]
@earlthesquirrel 

Please wait a little more.

https://github.com/adafruit/Adafruit_Blinka/pull/841

**Comment by nopnop2002** [comment]
@earlthesquirrel 

I found a problem and will fix it.

https://github.com/adafruit/Adafruit_Blinka/pull/842

![Pico-Max-SSD1306-1](https://github.com/adafruit/Adafruit_Blinka/assets/6020549/e2865271-61a5-4561-836e-79c071809b46)
![Pico-Max-SSD1306-2](https://github.com/adafruit/Adafruit_Blinka/assets/6020549/ac9921c5-0118-42a1-8e6c-b231e142db7e)
![Pico-Min-SSD1306-1](https://github.com/adafruit/Adafruit_Blinka/assets/6020549/b8162845-7fb4-4f5d-a40d-dec729919c58)
![Pico-Min-SSD1306-2](https://github.com/adafruit/Adafruit_Blinka/assets/6020549/a64beb98-9820-4fa1-9c78-d85ef07a7ca4)

**Comment by makermelissa** [comment]
These have now been added.

**Comment by earlthesquirrel** [comment]
I see this marked as complete.  @makermelissa @nopnop2002 can you tell me if there is a CircuitPython release that includes this board?  I see some links and that BlinkA is available but it's not clear how to get CircuitPython running on this board.

**Comment by nopnop2002** [comment]
@earlthesquirrel 

LuckFox comes with CPython installed.

**Comment by dhalbert** [comment]
Since these run Linux, you would use "regular Python" and the Adafruit Blinka library.
