### ISSUE TITLE
FT232H not being recognized in PowerShell

### ISSUE THREAD

**Issue by mano-sys** [adafruit/Adafruit_Blinka#822]

**Comment by makermelissa** [comment]
Which board are you using?

**Comment by alorcamo** [comment]
I get the exact same error (version 3.62.0). Running Windows 11 connected to a Adafruit FT232H. 

Any clues on how to fix it? I want to connect to a Qwiic sensor from a python script on the Windows 11 PC over the Adafruit FT232H. Following the [CircuitPython Libraries on any Computer with FT232H](https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h)  Windows](https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/windows) tutorial.

**Comment by alorcamo** [comment]
Nevermind, solved. I realized too late that the VS Code Terminal is Powershell and I had used `set BLINKA_FT232H=1` instead of  `$env:BLINKA_FT232H=1`...I managed to oversee the big warning (:  ... just in case it helps someone.

**Comment by makermelissa** [comment]
Awesome, thanks for reporting the fix for you.
