### ISSUE TITLE
Adafruit-PlatformDetect version 3.66.0 was unable to identify the board

### ISSUE THREAD

**Issue by Aobabj** [adafruit/Adafruit_Blinka#834]
<!-- We keep growing Blinka 🚀 and would love ❤ to
 see what new boards you would like supported... 
I meet the following issue when I import board:  (python 3.10)
Traceback (most recent call last):
  File "C:\Users\hahahahahahaha\PycharmProjects\Motion\i2c with Adafruit_FT232.I2CDevice.py", line 2, in <module>
    import board
  File "C:\ProgramData\Yinbai\lib\site-packages\board.py", line 405, in <module>
    raise NotImplementedError(
NotImplementedError: 
        Adafruit-PlatformDetect version 3.66.0 was unable to identify the board and/or
        microcontroller running the Windows platform. Please be sure you
        have the latest packages by running:
        'pip3 install --upgrade adafruit-blinka adafruit-platformdetect'

        If you are running the latest package, your board may not yet be supported. Please
        open a New Issue on GitHub at https://github.com/adafruit/Adafruit_Blinka/issues and
        select New Board Request.

**Comment by makermelissa** [comment]
Could you give some more information such as the board that was not detected?

**Comment by makermelissa** [comment]
Closing for now. Will re-open if a board name is provided.

**Comment by Aobabj** [comment]
hello Melissa,
thank you for your response.
i had solve the problem in my ocde. i do not think i need a new version for
Adafruit_blinka any more.

thanks!

Melissa LeBlanc-Williams ***@***.***> 于2024年6月5日周三 01:06写道：
