### ISSUE TITLE
Remove dependency to numpy

### ISSUE THREAD

**Issue by plaa** [adafruit/Adafruit_Blinka#872]
Please remove the dependency to `numpy` package.  It is an insanely bloated package (20MB compared to 200-300 kB for other packages) and I'm having tremendous problems installing it on a Raspi Zero W (installing it with poetry fails due to many compilation problems and I finally hit a brick wall I'm unable to solve, and installing using pip also requires e.g. g++ to be installed and takes tens of minutes).

The [only reference I can find to numpy](https://github.com/search?q=repo%3Aadafruit%2FAdafruit_Blinka+numpy&type=code) is the dependency, I can't see it used in any code.  numpy is for scientific calculation, I cannot see why a package like Adafruit blinka would need it.

Thanks.

**Comment by makermelissa** [comment]
Makes sense. I think this was added back when it was a dependency of displayio (it no longer is), but will look around to confirm you are correct before removing it.
