### ISSUE TITLE
FT232H not working in Thonny but can be seen in terminal

### ISSUE THREAD

**Issue by sjagrant** [adafruit/Adafruit_Blinka#903]
FT232H not working in Thonny but can be seen in terminal.  Running on Windows and followed Adafruit install instructions with positive feedback for tests.  

 raise NotImplementedError(
NotImplementedError: 
        Adafruit-PlatformDetect version 3.75.0 was unable to identify the board and/or
        microcontroller running the Windows platform. Please be sure you
        have the latest packages by running:
        'pip3 install --upgrade adafruit-blinka adafruit-platformdetect' 

Check and installed correctly

**Comment by caternuson** [comment]
Probably related to Thonny not seeing the environment variable.

Did you run the post install checks from within Thonny also?
https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/troubleshooting
In particular, this one:
https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/troubleshooting#check-environment-variable-within-python-3041702

**Comment by caternuson** [comment]
* In Thonny, go to Tools -> Options...
* Enter `BLINKA_FT232H=1` in the Environment variables
* Restart Thonny

![image](https://github.com/user-attachments/assets/4b121d3a-8093-4351-9a43-50c2ea8293e3)

Can test like this:
![image](https://github.com/user-attachments/assets/a1efaa2b-6b5c-4daf-84a4-2d3983ed41dd)

**Comment by sjagrant** [comment]
Many thanks Carter that sorted it out.

What excellent support.
Best regards,
stuart

**Comment by sjagrant** [comment]
Yes I did,  but when I got to  NotImplementedError recheck Zadig I didn't
get any further and kept going back to setup steps.---

-------------------------------------

If you get

NotImplementedError: Operation not supported or unimplemented on this
platform

Go back to the setup steps and Zadig your board if on Windows
<https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h/troubleshooting#check-environment-variable-within-python-3041702>
Check environment variable within python

At the Python REPL, type

import os
os.environ["BLINKA_FT232H"]

if you get a KeyError it means you did not set the environment variable
right

------------------------------------------------


Again many thanks for your great support.

**Comment by caternuson** [comment]
Closing since resolved.
