### ISSUE TITLE
Remote GPIO support

### ISSUE THREAD

**Issue by shetty-777** [adafruit/Adafruit_Blinka#906]
REALLY would appreciate having some way to use the remote GPIO functionality of the Raspberry Pi with this. Using BLINKA_FORCEBOARD=RASPBERRY_PI_3B_PLUS does nothing but change the problem. Now it looks for RPi.GPIO, which no surprise, IS NOT AVAILABLE ON WINDOWS

**Comment by ladyada** [comment]
this is not something we'd do within blinka - you really have to run it locally on the pi!
