### ISSUE TITLE
adafruit_blinka.microcontroller.bcm283x.pulseio is not packaged

### ISSUE THREAD

**Issue by cpforbes** [adafruit/Adafruit_Blinka#91]
adafruit_blinka.microcontroller.bcm283x.pulseio is missing from the package on PyPI.

`__init__.py` is missing from `adafruit_blinka/microcontroller/bcm283x/pulseio` so `setuptools.find_packages("src")` does not find the package.

Additionally, special handling is needed for the `libgpiod_pulsein` program since it is not python code.

**Comment by ladyada** [comment]
@cpforbes hiya - do you know what the fix would be? if so could you submit a PR? we can re-release to run the packager but we're not python packaging experts and dont want to get it wrong again :)
