### ISSUE TITLE
Unable to Import SCL and SDA

### ISSUE THREAD

**Issue by quantphantom** [adafruit/Adafruit_Blinka#913]
### Board Name

/dev/ttyACM0 (Arduino UNO R3)

### Steps

1. Set Up Your Environment

Ensure Python 3.x is installed (preferably 3.7+).
Install the latest versions of Adafruit Blinka and Adafruit PlatformDetect:
- pip install --upgrade adafruit-blinka adafruit-platformdetect

2. Write a Simple Test Script Create a Python script, test_blinka.py, with the following code to test Blinka:
- from board import SCL, SDA

3. Run the Script Execute the script from the command line:
- python test_blinka.py

4. Observe the Error Note the NotImplementedError message, which indicates that Adafruit PlatformDetect failed to identify the board and/or microcontroller.

### Description

Error Details:

NotImplementedError: 
        Adafruit-PlatformDetect version 3.75.0 was unable to identify the board and/or
        microcontroller running the Windows platform. Please be sure you
        have the latest packages by running:
        'pip3 install --upgrade adafruit-blinka adafruit-platformdetect'

        If you are running the latest package, your board may not yet be supported. Please
        open a New Issue on GitHub at https://github.com/adafruit/Adafruit_Blinka/issues and
        select New Board Request.

**Comment by dhalbert** [comment]
Closing due to no response.
